# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["hkakehashi+demo@fastly.com"]
description = "Application template for presenting CAPTCHA challenges to visitors at the edge"
language = "javascript"
manifest_version = 2
name = "captcha-at-edge"
service_id = ""

[local_server]
  [local_server.backends]
    [local_server.backends.captcha_backend]
      url = "https://www.google.com"
    [local_server.dictionaries.captcha_config]
      format = "inline-toml"
    [local_server.dictionaries.captcha_config.contents]
      "shared_secret" = "XXX"
      "recaptcha_secret_key" = "XXX"
      "token_lifetime" = "86400"